# Generated by Django 2.2.4 on 2020-02-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_customer_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
