# Generated by Django 2.2.14 on 2020-09-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20200902_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
